"""
bookmark automatically generated by SDKgen please do not edit this file manually
https://sdkgen.app
"""

from pydantic import BaseModel, Field, GetCoreSchemaHandler
from pydantic_core import CoreSchema, core_schema
from typing import Any, Dict, Generic, List, Optional, TypeVar, Union
class Bookmark(BaseModel):
    bookmarked: Optional[bool] = Field(default=None, alias="bookmarked")
    pass
