"""
error automatically generated by SDKgen please do not edit this file manually
https://sdkgen.app
"""

from pydantic import BaseModel, Field, GetCoreSchemaHandler, Tag
from pydantic_core import CoreSchema, core_schema
from typing import Any, Dict, Generic, List, Optional, TypeVar, Annotated, Union


class Error(BaseModel):
    type: Optional[str] = Field(default=None, alias="type")
    title: Optional[str] = Field(default=None, alias="title")
    status: Optional[int] = Field(default=None, alias="status")
    detail: Optional[str] = Field(default=None, alias="detail")
    pass


