"""
errors automatically generated by SDKgen please do not edit this file manually
https://sdkgen.app
"""

from pydantic import BaseModel, Field, GetCoreSchemaHandler, Tag
from pydantic_core import CoreSchema, core_schema
from typing import Any, Dict, Generic, List, Optional, TypeVar, Annotated, Union
from .error import Error


class Errors(BaseModel):
    errors: Optional[List[Error]] = Field(default=None, alias="errors")
    pass


