"""
SearchTag automatically generated by SDKgen please do not edit this file manually
https://sdkgen.app
"""

import requests
import sdkgen
from requests import RequestException
from typing import List

from .fields import Fields
from .pagination import Pagination
from .tweet_collection import TweetCollection

class SearchTag(sdkgen.TagAbstract):
    def __init__(self, http_client: requests.Session, parser: sdkgen.Parser):
        super().__init__(http_client, parser)


    def get_recent(self, query: str, sort_order: str, expansions: str, pagination: Pagination, fields: Fields) -> TweetCollection:
        try:
            path_params = {}

            query_params = {}
            query_params["query"] = query
            query_params["sort_order"] = sort_order
            query_params["expansions"] = expansions
            query_params["pagination"] = pagination
            query_params["fields"] = fields

            query_struct_names = []
            query_struct_names.append('pagination')
            query_struct_names.append('fields')

            url = self.parser.url("/2/tweets/search/recent", path_params)

            headers = {}

            response = self.http_client.get(url, headers=headers, params=self.parser.query(query_params, query_struct_names))

            if response.status_code >= 200 and response.status_code < 300:
                return TweetCollection.model_validate_json(json_data=response.content)


            raise sdkgen.UnknownStatusCodeException("The server returned an unknown status code")
        except RequestException as e:
            raise sdkgen.ClientException("An unknown error occurred: " + str(e))


