"""
trend automatically generated by SDKgen please do not edit this file manually
https://sdkgen.app
"""

from pydantic import BaseModel, Field, GetCoreSchemaHandler
from pydantic_core import CoreSchema, core_schema
from typing import Any, Dict, Generic, List, Optional, TypeVar, Union
class Trend(BaseModel):
    trend_name: Optional[str] = Field(default=None, alias="trend_name")
    tweet_count: Optional[int] = Field(default=None, alias="tweet_count")
    pass
