"""
tweet_reply automatically generated by SDKgen please do not edit this file manually
https://sdkgen.app
"""

from pydantic import BaseModel, Field, GetCoreSchemaHandler
from pydantic_core import CoreSchema, core_schema
from typing import Any, Dict, Generic, List, Optional, TypeVar, Union
class TweetReply(BaseModel):
    exclude_reply_user_ids: Optional[List[str]] = Field(default=None, alias="exclude_reply_user_ids")
    in_reply_to_tweet_id: Optional[str] = Field(default=None, alias="in_reply_to_tweet_id")
    pass
