"""
tweet_poll automatically generated by SDKgen please do not edit this file manually
https://sdkgen.app
"""

from pydantic import BaseModel, Field, GetCoreSchemaHandler
from pydantic_core import CoreSchema, core_schema
from typing import Any, Dict, Generic, List, Optional, TypeVar, Union
class TweetPoll(BaseModel):
    duration_minutes: Optional[int] = Field(default=None, alias="duration_minutes")
    options: Optional[List[str]] = Field(default=None, alias="options")
    pass
