"""
tweet_media automatically generated by SDKgen please do not edit this file manually
https://sdkgen.app
"""

from pydantic import BaseModel, Field, GetCoreSchemaHandler
from pydantic_core import CoreSchema, core_schema
from typing import Any, Dict, Generic, List, Optional, TypeVar, Union
class TweetMedia(BaseModel):
    media_ids: Optional[List[str]] = Field(default=None, alias="media_ids")
    tagged_user_ids: Optional[List[str]] = Field(default=None, alias="tagged_user_ids")
    pass
