"""
tweet_delete_response_message automatically generated by SDKgen please do not edit this file manually
https://sdkgen.app
"""

from pydantic import BaseModel, Field, GetCoreSchemaHandler
from pydantic_core import CoreSchema, core_schema
from typing import Any, Dict, Generic, List, Optional, TypeVar, Union
class TweetDeleteResponseMessage(BaseModel):
    deleted: Optional[bool] = Field(default=None, alias="deleted")
    pass
